### ISSUE TITLE
 Enable ppc64le arch on 3scale-operator-metadata

### ISSUE THREAD

**Issue by Abhijit-Mane** [3scale/3scale-operator-metadata#8]
Hi,

Thanks for the well articulated documentation that helped make/build 3scale-operator-metadata successfully on IBM Power
architecture (in short, ppc64le).

**What is IBM Power architecture?**
It is a RISC architecture and is IBM's prodigy, IBM has recently made its ISA (Instruction Set Architecture) opensource and in doing
so, they have significantly contributed back to the opensource community at large. Many of the pioneers of banking and HPC
industries today run on ppc64le architecture.

As an ongoing effort to enable open-source projects to which ppc64le architecture can add value, we are trying to enable this
project as well as the larger set of 3scale components belonging to the 3scale API Management software.
We have seen absolutely no deviation in build/test instructions. I plan to submit a PR to enable build/testing on ppc64le.

**What would it take from us to enable ppc64le in the CI/CD pipeline?**
I see CircleCI is being used for the CI pipeline of this project. As of now, this is not supported for native compilation on ppc64le.
However, currently, we are enabled/certified on Travis & Jenkins and lots of open source communities have successfully used these
as CI/CD for ppc64le.

**Comment by eguzki** [comment]
In CircleCI we do not build anything, just run some validation tools for the existing manifests.

I do not see any value running those validations on ppc64le. This repo is entirely targeted to host manifests.

Maybe you should look at https://github.com/3scale/3scale-operator

**Comment by Abhijit-Mane** [comment]
@eguzki Thanks for the update. I will close this issue.
